[GNNRank]
name = "gnnrank-consistency"
version = "0.1.0"
description = "Directed GNN ranking with Fiedler refinement and triangle consistency loss"
authors = [{name = "rnouri", email = "rnouri@coppin.edu"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "torch>=2.2",
  "numpy",
  "pandas",
  "pyyaml",
  "scipy",
  "scikit-learn",
  "networkx",
  "matplotlib",
  "tensorboard",
]

[tool.setuptools]
packages = ["src"]
